[Client]
	addr = "127.0.0.1:3307"
	dsn = "root:123456@tcp(127.0.0.1:3307)/kratos_demo?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
	# 如果配置了readDSN，在进行读操作的时候会优先使用readDSN的连接，readDSN可以只配一个地址。
# 	readDSN = ["{user}:{password}@tcp(127.0.0.2:3306)/{database}?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8","{user}:{password}@tcp(127.0.0.3:3306)/{database}?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
# 	active = 20 # 最大连接数active
	idle = 10 # 连接池的闲置连接数
	idleTimeout ="4h"
	queryTimeout = "200ms"
	execTimeout = "300ms"
	tranTimeout = "400ms"
